x-logging: &default-logging
  driver: json-file
  options:
    max-size: 50m
    max-file: 6
x-network: &default-network
  - internal
x-base: &base
  image: '${IMAGE_NAME:-app}:latest'
  build:
    context: .
    dockerfile: Dockerfile
    target: prod
    args:
      APP_ENV: production
      WWWUSER: '${HOST_UID:-1000}'
      WWWGROUP: '${HOST_GID:-1000}'
  user: '${HOST_UID:-1000}:${HOST_GID:-1000}'
  ulimits:
    nofile:
      soft: 20000
      hard: 40000
  security_opt:
    - 'no-new-privileges:true'
  volumes:
    - 'app_public:/app/storage/app/public'
    - 'app_logs:/app/storage/logs'
    - 'app_cache:/app/bootstrap/cache'
  logging:
    driver: json-file
    options:
      max-size: 50m
      max-file: 6
  restart: always
  depends_on:
    valkey:
      condition: service_healthy
    pgsql:
      condition: service_healthy
services:
  app:
    <<: *base
    healthcheck:
      test:
        - CMD
        - curl
        - '--fail'
        - 'localhost:80/up'
      start_period: 5s
      interval: 10s
      retries: 12
    environment:
      INERTIA_SSR: false
      SERVER_NAME: ':80'
      CADDY_SERVER_SERVER_NAME: ':80'
      APP_PUBLIC_PATH: /app/public
      ENV_ROOT: /app
      ENV_USER: www-data
      APP_HOST: '${APP_HOST}' 
    networks:
      - internal
      - web
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.stream.rule=Host(`${APP_HOST}`)'
      - traefik.http.routers.stream.entrypoints=websecure
      - traefik.http.routers.stream.tls.certresolver=le
      - traefik.http.services.stream.loadbalancer.server.port=80
  horizon:
    <<: *base
    environment:
      CONTAINER_MODE: horizon
    networks: *default-network
    depends_on:
      app:
        condition: service_healthy
  valkey:
    image: 'valkey/valkey:alpine'
    healthcheck:
      test:
        - CMD
        - valkey-cli
        - ping
      retries: 3
      timeout: 5s
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    command:
      - valkey-server
      - '--requirepass'
      - '${REDIS_PASSWORD:-cipassword}'
      - '--maxmemory'
      - 2gb
    security_opt:
      - 'no-new-privileges:true'
    volumes:
      - 'stack-valkey:/data'
    networks: *default-network
    restart: always
    logging: *default-logging
  pgsql:
    image: 'postgres:17'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER}'
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
      - 'postgres_shared:/shared'
    networks: *default-network
    restart: always
    logging: *default-logging
networks:
  internal: null
  web:
    external: true
volumes:
  app_public: null
  app_logs: null
  app_cache: null
  stack-valkey: null
  postgres_data: null
  postgres_shared: null