services:
  traefik:
    ports:
      - "80:80"
      - "443:443"
    networks:
      development:
    volumes:
      # Mount the Docker socket as read-only so Traefik can listen to events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.infrastructure/conf/traefik/dev/traefik.yml:/traefik.yml:ro
      - ./.infrastructure/conf/traefik/dev/traefik-certs.yml:/traefik-certs.yml
      - ./.infrastructure/conf/traefik/dev/certificates/:/certificates

  php:
    build:
      target: development
      args:
        USER_ID: ${SPIN_USER_ID}
        GROUP_ID: ${SPIN_GROUP_ID}
    volumes:
      - .:/var/www/html/
    networks:
      - development
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=HostRegexp(`localhost`)"
      - "traefik.http.routers.laravel.entrypoints=web"
      - "traefik.http.services.laravel.loadbalancer.server.port=8080"
      - "traefik.http.services.laravel.loadbalancer.server.scheme=http"

  node:
    image: node:22
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/
    networks:
      - development

  mailpit:
    image: axllent/mailpit
    networks:
      - development
    ports:
      - "8025:8025"

  postgres:
    image: postgres:16-alpine
    networks:
      - development
    environment:
      POSTGRES_DB: "${DB_DATABASE:-laravel}"
      POSTGRES_USER: "${DB_USERNAME:-laravel}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-password}"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    networks:
      - development
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

  ssh:
    # We use an SSH image so we can securely tunnel into the Docker network with 
    # tools like Sequel Pro, TablePlus, Sequel Ace, etc.
    # Learn more how to secure your tunnel here: https://github.com/serversideup/docker-ssh
    image: serversideup/docker-ssh:v2.0.0
    ports:
      - "2222:2222"
    environment:
      # Change the keys below to your own keys 
      AUTHORIZED_KEYS: >
        "# Start Keys
         ssh-ed25519 1234567890abcdefghijklmnoqrstuvwxyz user-a
         ssh-ed25519 abcdefghijklmnoqrstuvwxyz1234567890 user-b
         # End Keys"
      # You can lock to a specific IP too (AllowUsers tunnel@1.2.3.4)
      ALLOWED_IPS: "AllowUsers tunnel"
    volumes:
      - tunnel_ssh_host_keys_dev:/etc/ssh/ssh_host_keys
    networks:
      - development
    depends_on:
      - postgres

volumes:
  postgres_dev_data:
  redis_dev_data:
  tunnel_ssh_host_keys_dev:

networks:
  development:
